version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: kloud_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: k8s_monitoring
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kloud-net

volumes:
  pg_data:

networks:
  kloud-net:
    driver: bridge